### PR TITLE
Added a Load More Posts Button

### PR DESCRIPTION
**Pull request by mihailot01**

### CODE REVIEW

**Comment by knightspore** [comment]
Looks good! Just remove the `.yarn/releases/yarn-1.22.10.cjs` file from the commit and I can merge :)

**Review by mihailot01 — COMMENTED** [review]
I hope I removed unnecessary files

**Comment by knightspore** [comment]
thanks for your contribution!!

**Comment by mihailot01** [comment]
Can I get hacktoberfest-accepted label in order to participate in Hacktober fest?

**Comment by knightspore** [comment]
Done, let me know if it worked properly

**Comment by mihailot01** [comment]
Yes, it's ok now. Thank you!

**Pull request merged**
